import type { CourseEvent, StudyBlock, ImportantDate } from "@/types/schedule"

export const SEED_COURSES: CourseEvent[] = [
  {
    id: "mon-m2413",
    title: "MATH 2413-004",
    courseCode: "MATH 2413",
    section: "004",
    type: "inperson",
    day: "Mon",
    startCT: "10:00",
    endCT: "10:50",
    location: "SCI 3.230",
    instructor: "Rabin Dahal",
    difficulty: 4,
    sentiment: "tough but fair; practice-heavy",
  },
  {
    id: "mon-m2413lab",
    title: "MATH 2413 Lab-305",
    courseCode: "MATH 2413",
    section: "305",
    type: "inperson",
    day: "Mon",
    startCT: "13:00",
    endCT: "14:50",
    location: "SCI 3.270",
  },
  {
    id: "mon-nsc4359",
    title: "NSC 4359-501 (Cognitive Neuro)",
    courseCode: "NSC 4359",
    section: "501",
    type: "inperson",
    day: "Mon",
    startCT: "17:30",
    endCT: "18:45",
    location: "CRA 12.110",
    difficulty: 3,
    sentiment: "figures detail matters",
  },

  {
    id: "tue-nsc4385",
    title: "NSC 4385-001 (Neuropsychology)",
    courseCode: "NSC 4385",
    section: "001",
    type: "inperson",
    day: "Tue",
    startCT: "11:30",
    endCT: "12:45",
    location: "ECSS 2.410",
    instructor: "Kristen M Kennedy",
    difficulty: 3,
    sentiment: "case-oriented; attend lecture",
  },
  {
    id: "tue-nsc4372",
    title: "NSC 4372-0W1 (Neuroimmunology)",
    courseCode: "NSC 4372",
    section: "0W1",
    type: "online",
    day: "Tue",
    startCT: "13:00",
    endCT: "14:15",
    location: "Online",
    instructor: "Michael D. Burton",
    difficulty: 3,
    sentiment: "dense papers; steady pace",
  },
  {
    id: "tue-epps4337",
    title: "EPPS 4337-001 (Internship)",
    courseCode: "EPPS 4337",
    section: "001",
    type: "online",
    day: "Tue",
    startCT: "19:00",
    endCT: "20:30",
    location: "Online",
    difficulty: 3,
    sentiment: "spikes near deliverables",
  },

  {
    id: "wed-m2413",
    title: "MATH 2413-004",
    courseCode: "MATH 2413",
    section: "004",
    type: "inperson",
    day: "Wed",
    startCT: "10:00",
    endCT: "10:50",
    location: "SCI 3.230",
  },
  {
    id: "wed-nsc4359",
    title: "NSC 4359-501",
    courseCode: "NSC 4359",
    section: "501",
    type: "inperson",
    day: "Wed",
    startCT: "17:30",
    endCT: "18:45",
    location: "CRA 12.110",
  },

  {
    id: "thu-nsc4385",
    title: "NSC 4385-001",
    courseCode: "NSC 4385",
    section: "001",
    type: "inperson",
    day: "Thu",
    startCT: "11:30",
    endCT: "12:45",
    location: "ECSS 2.410",
  },
  {
    id: "thu-nsc4372",
    title: "NSC 4372-0W1",
    courseCode: "NSC 4372",
    section: "0W1",
    type: "online",
    day: "Thu",
    startCT: "13:00",
    endCT: "14:15",
    location: "Online",
  },
  {
    id: "thu-epps4337",
    title: "EPPS 4337-001",
    courseCode: "EPPS 4337",
    section: "001",
    type: "online",
    day: "Thu",
    startCT: "19:00",
    endCT: "20:30",
    location: "Online",
  },

  {
    id: "fri-m2413",
    title: "MATH 2413-004",
    courseCode: "MATH 2413",
    section: "004",
    type: "inperson",
    day: "Fri",
    startCT: "10:00",
    endCT: "10:50",
    location: "SCI 3.230",
  },
  {
    id: "fri-exam",
    title: "MATH 2413-701 Exam (as scheduled)",
    courseCode: "MATH 2413",
    section: "701",
    type: "exam",
    day: "Fri",
    startCT: "19:00",
    endCT: "20:15",
    location: "SLC 2.303 / SLC 1.102",
  },

  {
    id: "isns-course",
    title: "ISNS 2367-0W3",
    courseCode: "ISNS 2367",
    section: "0W3",
    type: "online",
    day: "Fri",
    startCT: "00:00",
    endCT: "00:00",
    location: "Online",
    difficulty: 2,
    sentiment: "manageable with weekly work",
  },
]

export const SEED_STUDY_BLOCKS: StudyBlock[] = [
  {
    id: "study-mon-am",
    title: "Study — MATH",
    type: "study",
    day: "Mon",
    startCT: "11:00",
    endCT: "12:50",
    notes: "Problem set (2h)",
  },
  {
    id: "study-mon-pm",
    title: "Deep work — EPPS/ISNS",
    type: "study",
    day: "Mon",
    startCT: "15:00",
    endCT: "17:15",
    notes: "Project (2h)",
  },
  {
    id: "study-tue",
    title: "NSC 4372 reading",
    type: "study",
    day: "Tue",
    startCT: "15:30",
    endCT: "16:30",
    notes: "1h",
  },
  {
    id: "study-wed-am",
    title: "Study — MATH",
    type: "study",
    day: "Wed",
    startCT: "11:00",
    endCT: "13:00",
    notes: "Practice (2h)",
  },
  {
    id: "study-wed-pm",
    title: "Study — NSC 4359",
    type: "study",
    day: "Wed",
    startCT: "14:00",
    endCT: "17:00",
    notes: "Figures/notes (3h)",
  },
  {
    id: "study-thu",
    title: "EPPS deliverable",
    type: "study",
    day: "Thu",
    startCT: "15:30",
    endCT: "16:30",
    notes: "1h",
  },
  {
    id: "study-fri",
    title: "ISNS 2367 module",
    type: "study",
    day: "Fri",
    startCT: "14:00",
    endCT: "15:30",
    notes: "1.5h",
  },
  {
    id: "study-sat-am",
    title: "Deep work — EPPS/ISNS",
    type: "study",
    day: "Sat",
    startCT: "10:00",
    endCT: "12:00",
    notes: "2h",
  },
  {
    id: "study-sat-pm",
    title: "MATH practice (optional)",
    type: "study",
    day: "Sat",
    startCT: "14:00",
    endCT: "15:00",
    notes: "1h optional",
  },
  {
    id: "study-sun",
    title: "Weekly reset",
    type: "study",
    day: "Sun",
    startCT: "15:00",
    endCT: "17:00",
    notes: "Plan + skim",
  },
]

export const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

export const IMPORTANT_DATES: ImportantDate[] = [
  {
    id: "classes-begin",
    title: "Classes begin",
    date: "2024-08-25",
    type: "event",
  },
  {
    id: "census-day",
    title: "Census Day / Last day to drop without 'W'",
    date: "2024-09-10",
    type: "deadline",
  },
  {
    id: "undergrad-drop-start",
    title: "Undergrad drop/withdrawal (approval required)",
    date: "2024-09-11",
    description: "Through Nov 10",
    type: "deadline",
  },
  {
    id: "last-withdraw",
    title: "Last day to withdraw (undergrad)",
    date: "2024-11-10",
    type: "deadline",
  },
  {
    id: "last-classes",
    title: "Last day of classes (no finals)",
    date: "2024-12-09",
    type: "event",
  },
  {
    id: "reading-day",
    title: "Reading day",
    date: "2024-12-10",
    type: "event",
  },
  {
    id: "finals-start",
    title: "Final exams",
    date: "2024-12-11",
    description: "Through Dec 16",
    type: "exam",
  },
  {
    id: "labor-day",
    title: "Labor Day",
    date: "2024-09-01",
    type: "break",
  },
  {
    id: "fall-break",
    title: "Fall break (no classes)",
    date: "2024-11-24",
    description: "Mon–Wed, Nov 24–26",
    type: "break",
  },
  {
    id: "thanksgiving",
    title: "Thanksgiving break",
    date: "2024-11-27",
    description: "Thu–Sun, Nov 27–30",
    type: "break",
  },
  {
    id: "winter-break",
    title: "Winter break (campus closed)",
    date: "2024-12-22",
    description: "Through Jan 1",
    type: "break",
  },
]
