import type { CourseEvent, StudyBlock, ImportantDate } from "@/types/schedule"

export const SEED_COURSES: CourseEvent[] = [
  {
    id: "mon-cs101",
    title: "CS 101 - Intro to Programming",
    courseCode: "CS 101",
    section: "001",
    type: "inperson",
    day: "Mon",
    startCT: "09:30",
    endCT: "10:45",
    location: "Engineering Hall ",
    instructor: "Dr. Jamie ",
    difficulty: 3,
    sentiment: "Hands-on labs and weekly quizzes",
  },
  {
    id: "mon-math151",
    title: "MATH 151 - Calculus I",
    courseCode: "MATH 151",
    section: "004",
    type: "inperson",
    day: "Mon",
    startCT: "11:00",
    endCT: "11:50",
    location: "Science Center ",
    instructor: "Prof. Amrita ",
    difficulty: 4,
    sentiment: "Daily practice keeps the quizzes manageable",
  },
  {
    id: "mon-firstyear",
    title: "UNIV 1101 - First-Year Seminar",
    courseCode: "UNIV 1101",
    section: "101",
    type: "inperson",
    day: "Mon",
    startCT: "14:30",
    endCT: "15:20",
    location: "Student Success ",
    instructor: "Dr. Tasha  ",
    difficulty: 1,
    sentiment: "Low-stakes check-ins and campus tips",
  },
  {
    id: "tue-engl1302",
    title: "ENGL 1302 - Academic Writing",
    courseCode: "ENGL 1302",
    section: "007",
    type: "inperson",
    day: "Tue",
    startCT: "09:00",
    endCT: "10:15",
    location: "Liberal Arts ",
    instructor: "Dr. David ",
    difficulty: 2,
    sentiment: "Workshops focus on peer feedback",
  },
  {
    id: "tue-psych2301",
    title: "PSYC 2301 - Introduction to Psychology",
    courseCode: "PSYC 2301",
    section: "003",
    type: "inperson",
    day: "Tue",
    startCT: "13:30",
    endCT: "14:45",
    location: "Social Science ",
    instructor: "Prof. Adrian ",
    difficulty: 2,
    sentiment: "Lecture heavy but exams come directly from slides",
  },
  {
    id: "tue-chem1110lab",
    title: "CHEM 1110 - General Chemistry Lab",
    courseCode: "CHEM 1110",
    section: "B12",
    type: "inperson",
    day: "Tue",
    startCT: "15:00",
    endCT: "17:45",
    location: "STEM Lab ",
    instructor: "Jordan ",
    difficulty: 3,
    sentiment: "Arrive early to set up lab reports",
  },
  {
    id: "wed-cs101",
    title: "CS 101 - Intro to Programming",
    courseCode: "CS 101",
    section: "001",
    type: "inperson",
    day: "Wed",
    startCT: "09:30",
    endCT: "10:45",
    location: "Engineering Hall ",
    instructor: "Dr. Jamie ",
    difficulty: 3,
    sentiment: "Hands-on labs and weekly quizzes",
  },
  {
    id: "wed-math151",
    title: "MATH 151 - Calculus I",
    courseCode: "MATH 151",
    section: "004",
    type: "inperson",
    day: "Wed",
    startCT: "11:00",
    endCT: "11:50",
    location: "Science Center ",
  },
  {
    id: "thu-engl1302",
    title: "ENGL 1302 - Academic Writing",
    courseCode: "ENGL 1302",
    section: "007",
    type: "inperson",
    day: "Thu",
    startCT: "09:00",
    endCT: "10:15",
    location: "Liberal Arts ",
  },
  {
    id: "thu-psych2301",
    title: "PSYC 2301 - Introduction to Psychology",
    courseCode: "PSYC 2301",
    section: "003",
    type: "inperson",
    day: "Thu",
    startCT: "13:30",
    endCT: "14:45",
    location: "Social Science   ",
  },
  {
    id: "thu-cs101lab",
    title: "CS 101 Lab - Problem Solving Studio",
    courseCode: "CS 101",
    section: "L15",
    type: "inperson",
    day: "Thu",
    startCT: "16:00",
    endCT: "17:15",
    location: "Innovation Lab ",
    instructor: "Maya ",
    difficulty: 3,
    sentiment: "Pair programming; follow the checklist",
  },
  {
    id: "fri-math151",
    title: "MATH 151 - Calculus I",
    courseCode: "MATH 151",
    section: "004",
    type: "inperson",
    day: "Fri",
    startCT: "11:00",
    endCT: "11:50",
    location: "Science Center ",
  },
  {
    id: "fri-firstyear",
    title: "UNIV 1101 - First-Year Seminar",
    courseCode: "UNIV 1101",
    section: "101",
    type: "inperson",
    day: "Fri",
    startCT: "13:00",
    endCT: "13:50",
    location: "Student Success ",
  },
  {
    id: "fri-cs101-review",
    title: "CS 101 - Weekly Recitation",
    courseCode: "CS 101",
    section: "R05",
    type: "inperson",
    day: "Fri",
    startCT: "15:00",
    endCT: "16:15",
    location: "Engineering Hall ",
    sentiment: "Bring laptop for live coding practice",
  },
  {
    id: "sun-hist1301",
    title: "HIST 1301 - U.S. History to 1865",
    courseCode: "HIST 1301",
    section: "0W2",
    type: "online",
    day: "Sun",
    startCT: "00:00",
    endCT: "00:00",
    location: "Online — self-paced",
    difficulty: 2,
    sentiment: "Weekly module opens Sunday night",
  },
  {
    id: "tue-math151-exam1",
    title: "MATH 151 - Exam 1",
    courseCode: "MATH 151",
    section: "004",
    type: "exam",
    day: "Tue",
    startCT: "18:00",
    endCT: "19:30",
    location: "Testing Center ",
  },
]

export const SEED_STUDY_BLOCKS: StudyBlock[] = [
  {
    id: "study-mon-library",
    title: "Library focus session",
    type: "study",
    day: "Mon",
    startCT: "12:15",
    endCT: "13:45",
    notes: "Review CS 101 lecture notes and prep lab checklist",
  },
  {
    id: "study-tue-writing",
    title: "Writing studio draft time",
    type: "study",
    day: "Tue",
    startCT: "10:30",
    endCT: "11:30",
    notes: "Outline ENGL 1302 essay paragraphs",
  },
  {
    id: "study-wed-lab",
    title: "Programming lab practice",
    type: "study",
    day: "Wed",
    startCT: "15:30",
    endCT: "17:00",
    notes: "Finish CS 101 lab reflection",
  },
  {
    id: "study-thu-review",
    title: "Calculus problem set",
    type: "study",
    day: "Thu",
    startCT: "19:30",
    endCT: "21:00",
    notes: "Complete weekly WebAssign",
  },
  {
    id: "study-fri-reading",
    title: "Psych reading + quiz",
    type: "study",
    day: "Fri",
    startCT: "10:00",
    endCT: "11:00",
    notes: "Skim chapter summaries before lecture",
  },
  {
    id: "study-sat-reset",
    title: "Weekly planning + catch-up",
    type: "study",
    day: "Sat",
    startCT: "10:00",
    endCT: "12:00",
    notes: "Plan next week and clear Canvas tasks",
  },
  {
    id: "study-sun-preview",
    title: "Preview upcoming modules",
    type: "study",
    day: "Sun",
    startCT: "17:00",
    endCT: "18:00",
    notes: "Check HIST 1301 module and prep Monday to-dos",
  },
]

export const DAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

export const IMPORTANT_DATES: ImportantDate[] = [
  {
    id: "orientation-week",
    title: "New student orientation",
    date: "2025-08-18",
    description: "Campus tours and advising sessions",
    type: "event",
  },
  {
    id: "classes-begin",
    title: "Classes begin",
    date: "2025-08-25",
    type: "event",
  },
  {
    id: "labor-day",
    title: "Labor Day (no classes)",
    date: "2025-09-01",
    type: "break",
  },
  {
    id: "census-day",
    title: "Census Day / last day to drop without W",
    date: "2025-09-09",
    type: "deadline",
  },
  {
    id: "midterm-check",
    title: "Midterm grade check",
    date: "2025-10-10",
    description: "Review progress with advisors",
    type: "deadline",
  },
  {
    id: "fall-break",
    title: "Fall break",
    date: "2025-10-13",
    description: "No classes Oct 13–14",
    type: "break",
  },
  {
    id: "registration-open",
    title: "Spring registration opens",
    date: "2025-10-28",
    type: "deadline",
  },
  {
    id: "withdraw-deadline",
    title: "Last day to withdraw",
    date: "2025-11-07",
    type: "deadline",
  },
  {
    id: "thanksgiving",
    title: "Thanksgiving break",
    date: "2025-11-26",
    description: "No classes Nov 26–28",
    type: "break",
  },
  {
    id: "reading-day",
    title: "Reading day",
    date: "2025-12-08",
    type: "event",
  },
  {
    id: "finals-start",
    title: "Final exam week",
    date: "2025-12-09",
    description: "Exams run Dec 9–16",
    type: "exam",
  },
  {
    id: "commencement",
    title: "Winter commencement",
    date: "2025-12-20",
    type: "event",
  },
]
